config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  resources :users do
    resources :messages
  end
  root 'rooms#index'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  before_create :confirm_participant
  after_create_commit { broadcast_append_to self.room }
  after_destroy_commit { broadcast_remove_to self.room }
  validates :content, length: {minimum: 1}

  def confirm_participant
    if self.room.is_private
      is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
      throw :abort unless is_participant
    end
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  validates :name, length: {minimum: 3}
  scope :public_rooms, -> {where(is_private: false)}
  after_create_commit { broadcast_append_to('rooms') unless self.is_private }
  after_destroy_commit { broadcast_remove_to('rooms') unless self.is_private}
  has_many :messages, dependent: :destroy
  has_many :participants, dependent: :destroy

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id )
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :username
  validates :username, length: {minimum: 3}, presence: true
  validates :password_digest, presence: true, on: [:update,:save]
  validates :password, length: {minimum: 6}, presence: true, on: :create
  scope :all_except, -> (user) { where.not(id: user) }
  after_create_commit { broadcast_append_to('users') }
  after_destroy_commit { broadcast_remove_to('users') }
  after_update_commit { broadcast_replace_to('users') }
  has_many :messages, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?
  before_action :update_last_seen_at, if: -> { logged_in? && (current_user.last_seen_at.nil? || current_user.last_seen_at < 1.minutes.ago) }

  def current_user
    if session[:user_id]
      return @current_user  = User.find(session[:user_id])
    end
  end

  def update_last_seen_at
    if current_user
      current_user.update(last_seen_at: Time.current)
    end
  end

  def log_in(user)
    session[:user_id] = user.id
    @current_user = user
    redirect_to rooms_path, notice: 'Logged in successfully'
  end

  def logged_in?
    if current_user.nil?
      return false
    else
      return true
    end
  end

  def log_out
    @current_user = current_user
    session.delete(:user_id)
    @current_user = nil
    redirect_to rooms_path
  end

  def authorized
    redirect_to '/signin' unless logged_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @current_user = current_user
    @message = @current_user.messages.create(content: msg_params[:content], room_id: params[:room_id])
  end

  def destroy
    @current_user = current_user
    @message = @current_user.messages.find(params[:id])
    @message.destroy
  end

  private

  def msg_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @room = Room.new
    @current_user = current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    redirect_to signin_path unless @current_user
  end

  def create
    @room = Room.create(params.require(:room).permit(:name))
    redirect_to rooms_path
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
  end

  def show
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @messages = @single_room.messages

    redirect_to signin_path unless @current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def create
    @user = User.find_by(username: params[:user][:username])
    respond_to do |format|
      if @user && @user.authenticate(params[:user][:password])
        format.html{log_in(@user)}
      else
        format.html{render 'sessions/new', status: :unprocessable_entity}
      end
    end
  end

  def new

  end

  def destroy
    respond_to do |format|
      if logged_in?
        format.html{log_out}
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @message = Message.new
    @room_name = get_name(@user, @current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)
    @messages = @single_room.messages
  end

  def index
    @users = User.all_except(current_user)
    unless current_user.is_admin
      redirect_to rooms_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :password))
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html{redirect_to rooms_path}
      else
        format.html{render 'users/new', status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private
  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_delete_button.html.erb
<% if @current_user && @current_user.is_admin %>
  <div class="absolute right-1 border rounded-full hover:bg-gray-800 duration-200">
    <%= link_to image_tag("delete.png",:class => "w-6 h-6 p-1"),obj , data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </div>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li>-<%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <style>
    <%= ".msg-#{current_user&.id}" %> {
        background-color: #007bff !important;
    }
    <%= ".cont-#{current_user&.id}" %> {
        justify-content: flex-end;
    }
    <%= ".name-#{current_user&.id}" %> {
        display: none;
        text-align: right;
    }
    <%= ".delete-icon-#{current_user&.id}" %> {
        display: inline; !important;
    }
  </style>
</head>

<body>
<main class="mx-auto flex min-w-screen min-h-screen bg-gray-800">
  <%= yield %>
</main>
</body>
</html>

app/views/messages/_message.html.erb
<div id="message_<%= message.id %>" class="cont-<%= message.user.id %> rounded-lg my-2 flex">
  <div class="msg-<%= message.user.id %> rounded-lg bg-gray-600 inline-block p-2" >
    <% unless message.room.is_private %>
      <h6 class="name-<%= message.user.id %> font-semibold text-lg">
        <% if message.user %>
          <%= link_to message.user.username, message.user %>
        <% end %>
      </h6>
    <% end %>
    <div class="flex flex-row align-center">
      <%= message.content %>
      <div class="delete-icon-<%= message.user.id %> hidden border border-white inline-block ml-2 rounded-full hover:bg-gray-800 hover:border-gray-800 duration-200">
        <%= link_to image_tag("delete.png",:class => "w-6 h-6 p-1"),[message.user, message] , data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
      </div>
    </div>
  </div>
</div>

app/views/messages/_new_message_form.html.erb
<div class="form-group msg-form flex flex-col bg-gray-800 px-4">
  <%= form_with(model: [@single_room ,@message],remote: true, class: "flex flex-row my-4",
                data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content text-gray-800 w-full rounded-lg", autocomplete: 'off' %>
    <%= f.submit "Send", data: { disable_with: false }, class: "hover:cursor-pointer rounded-lg duration-200 border border-gray-100 text-gray-100 hover:bg-gray-100 hover:text-gray-800 ml-2 px-2" %>
  <% end %>
</div>

app/views/rooms/_new_room_form.html.erb
<%= form_with(model: @room, remote:true,
              data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
  <div class="mb-8 text-white flex flex-col text-center border border-gray-400 rounded-lg px-12 py-4 mt-8 bg-sky-900 space-y-4">
    <%= f.label :name, "Add a new room", :class=>"font-light text-lg" %>
    <div class="flex md:flex-row flex-col w-full md:space-x-2 md:space-y-0 space-y-2">
      <%= f.text_field :name, class: "rounded-lg md:w-3/4 w-full text-sky-900", autocomplete: 'off' %>
      <div class="md:w-1/4 w-full border border-white rounded-lg text-white hover:bg-white hover:text-sky-900 duration-200">
        <%= f.submit 'Add', :class=>"hover:cursor-pointer w-full h-full" %>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="room_<%= room.id %>" class="relative flex flex-row justify-between">
  <%= link_to room.name, room, :class => "text-white hover:underline w-full text-center" %>
  <%= render :partial => 'layouts/delete_button', :locals => {obj:room} %>
</div>

app/views/rooms/index.html.erb
<div class="flex flex-col md:w-1/2 xl:w-1/3 w-full mx-auto relative md:my-auto md:px-0 px-4">
  <div class="absolute text-white md:top-0 top-2 md:right-0 right-2 align-center border border-white rounded-lg px-2 py hover:bg-white hover:text-gray-800 duration-200">
    <%= link_to "Sign Out", signout_path, data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </div>

  <% if @current_user %>
    <div class="text-3xl font-light mb-4 text-left md:pt-0 pt-2 text-white">Hi, <%= @current_user.username %>.</div>
  <% end %>

  <div class="md:px-0 px-8 w-full flex md:flex-row flex-col justify-around md:space-x-4 md:space-y-0 space-y-8">

    <div class="mx-auto relative md:w-1/2 w-full border border-gray-400 rounded-lg h-80 bg-sky-900 overflow-y-scroll text-center ">
      <p class="sticky text-white text-center border-b border-gray-400 top-0 inset-x-1 text-xl font-normal mb-2 z-10 bg-sky-900 w-full py-1">Users</p>
      <%= turbo_stream_from "users" %>
      <div id="users" class="space-y-2">
        <%= render @users %>
      </div>
      <% if @current_user.is_admin && @users.length>0 %>
        <div class="text-white font-semibold hover:underline py-1 mt-2 w-full text-center sticky bottom-0 bg-sky-900 border-t border-gray-400 z-10">
          <%= link_to 'Manage Users', users_path %>
        </div>
      <% end %>
    </div>


    <div class="mx-auto relative md:w-1/2 w-full border border-gray-400 rounded-lg pb-2 h-80 bg-sky-900 overflow-y-scroll">
      <p class="sticky top-0 inset-x-1 text-xl text-center font-normal mb-2 bg-sky-900 w-full py-1 border-b border-gray-400 text-white">Public Rooms</p>
      <%= turbo_stream_from "rooms" %>
      <div id="rooms" class="space-y-2">
        <%= render @rooms %>
      </div>
    </div>

  </div>
  <% if @current_user.is_admin %>
    <%= render partial: "rooms/new_room_form" %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<% if @single_room %>
  <div class="relative flex flex-col px-2 text-white border-r border-l bg-gray-800 md:w-1/2 w-full mx-auto max-h-screen justify-between">
    <div class="absolute top-2 left-2 z-10">
      <%= link_to '⬅', rooms_path, :class => "text-2xl" %>
    </div>

    <h4 class="sticky top-0 left 0 w-full bg-gray-800 text-center text-3xl font-semibold mt-2"> <%= @single_room.name %></h4>

    <%= turbo_stream_from @single_room %>
    <div class="overflow-y-scroll px-4 flex flex-col-reverse h-full">
      <div id="messages">
        <%= render @messages %>
      </div>
    </div>
    <%= render partial: 'messages/new_message_form' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="user_<%= user.id %>" class="relative flex flex-row justify-center px-2">
  <p class="text-gray-300 w-full">
    <%= link_to user.username, user, :class => "text-white hover:underline font-semibold" %> -
    <%= user.last_seen_at.nil? ? "Never seen" : time_ago_in_words(user.last_seen_at) %>
  </p>
</div>

app/views/users/index.html.erb
<div class="mx-auto relative my-auto md:w-1/3 w-full border border-gray-400 rounded-lg pb-2 h-80 bg-sky-900 overflow-y-scroll">
  <div class="sticky relative">
    <div class="absolute left-2 z-10 text-white">
      <%= link_to '⬅', rooms_path, :class => "text-2xl" %>
    </div>
    <p class="text-white text-center border-b border-gray-400 top-0 inset-x-1 text-xl font-normal mb-2 bg-sky-900 w-full py-1">All Users</p>
  </div>
  <%= turbo_stream_from "users" %>
  <div id="users" class=" space-y-2">
    <% @users.each do |user| %>
      <div id="user_<%= user.id %>" class="relative flex flex-row justify-center px-2">
        <p class="text-gray-300 w-full">
          <%= link_to user.username, user, :class => "text-white hover:underline font-semibold" %>
          <%= render :partial => 'layouts/delete_button', :locals => {obj:user} %>
        </p>
      </div>
    <% end %>
  </div>

</div>

app/views/users/new.html.erb
<div class="justify-center flex flex-col md:my-auto md:mx-auto border border-gray-600 md:rounded-xl py-12 md:px-16 px-8 bg-sky-900 md:w-1/3 w-full text-white">
<div class="mx-auto relative w-full">
    <h1 class="text-2xl font-semibold text-center mb-4">Sign Up</h1>
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="text-red-500 font-semibold mb-4">
        <%= render partial: "layouts/form_errors", locals: { object: @user } %>
      </div>

      <div class="flex flex-col space-y-4">
        <div class="flex flex-col">
          <%= f.label :username, 'Username' %>
          <%= f.text_field :username, :class=>"rounded-xl w-full text-sky-900" %>
        </div>
        <div class="flex flex-col">
          <%= f.label :password, 'Password' %>
          <%= f.password_field :password,:class=>"rounded-xl w-full text-sky-900" %>
        </div>
        <%= f.submit 'Create User', :class=>"py-2 border border-white rounded-lg hover:bg-white hover:text-sky-900 duration-200 hover:cursor-pointer" %>
      </div>
    <% end %>
  </div>
  <div class="mt-4 text-center">
    <p>Do you have an account? <%= link_to 'Sign in',signin_path, :class => "text-blue-300 hover:underline" %></p>
  </div>
</div>

app/views/users/show.html.erb
<% if @single_room %>
  <div class="relative flex border-r border-l px-2 flex-col text-white bg-gray-800 md:w-1/2 w-full mx-auto max-h-screen justify-between">
    <div class="absolute top-2 left-2 z-10">
      <%= link_to '⬅', rooms_path, :class => "text-2xl" %>
    </div>

    <h4 class="sticky top-0 left 0 w-full bg-gray-800 text-center text-3xl font-semibold mt-2"> <%= @user.username %></h4>

    <%= turbo_stream_from @single_room %>
    <div class="overflow-y-scroll px-4 flex flex-col-reverse h-full">
      <div id="messages">
        <%= render @messages %>
      </div>
    </div>
    <%= render partial: 'messages/new_message_form' %>
  </div>
<% end %>